---
- name: bootstrap Main Node
  hosts: main # what we run our playbook on
  # defined by out ansible file
  become: yes
  vars:
    listen_address: 0.0.0.0
    listen_port: 9090
  
  tasks:
  - name: Download apt key
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: Add Grafana repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana # appends .list
      state: present
  - name: Update apt cache and install Grafana
    ansible.builtin.apt:
      name: grafana
      update_cache: yes
  - name: Ensure Grafana is started and enabled
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html#ansible-collections-ansible-builtin-systemd-service-module
    ansible.builtin.systemd_service:
      name: grafana-server
      state: started
      enabled: true
  - name: Download Prometheus
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
    ansible.builtin.get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu # different for other machines
  - name: Extract Prom Resources
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html
    ansible.builtin.unarchive:
      src: /home/ubuntu/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu
      remote_src: yes
  - name: Create Prom Group
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/group_module.html
    ansible.builtin.group:
      name: prometheus
      state: present
  - name: Create Prom User
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
    ansible.builtin.user:
      name: prometheus
      group: prometheus
      shell: /sbin/nologin
  - name: Creare Prom Directories
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: yes #allows us to set owner and group recursively
      owner: prometheus
      group: prometheus
      mode: "0755"
    loop:
      - /etc/prometheus
      - /etc/prometheus/rules
      - /etc/prometheus/rules.d
      - /etc/prometheus/files_sd
      - /var/lib/prometheus
  - name: Copy Files
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
    ansible.builtin.copy:
      # keep it simple
      src: "{{ item }}"
      dest: /usr/local/bin/
      remote_src: yes
      mode: '0755'
      owner: prometheus
      group: prometheus
    loop: 
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/prometheus
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/promtool
  - name: Copy Files
    ansible.builtin.copy:
    # keep it simple
      src: "{{ item }}"
      dest: /etc/prometheus
      remote_src: yes
    loop: 
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/consoles
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/console_libraries
  - name: Create Config File
    ansible.builtin.template:
      src: prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
      # src local, dest remote
  - name: Create Systemd File
    ansible.builtin.template:
      src: prometheus.service.j2
      dest: /etc/systemd/system/prometheus.service
  - name: Ensure Prometheus is Started
    ansible.builtin.systemd_service:
      name: prometheus
      state: started
      enabled: true

